/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import cairomonorail.Ticket;
import java.awt.GridLayout;
/**
 *
 * @author Go
 */
public class TicketCard extends javax.swing.JPanel {

    /**
     * Creates new form TicketCard
     */
    private Ticket ticket;
    public TicketCard(Ticket ticket) {
        initComponents();
        setTicket(ticket);
    }

    public Ticket getTicket() {
        return ticket;
    }

    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
        ticketDetailsPanel.setLayout(new GridLayout(4,1));
        ticketDetailsPanel.add(new RouteCard(this.ticket.getRoute()));
        ticketDetailsPanel.add(new StationCard(this.ticket.getDepartStation()));
        TrainCard tc=new TrainCard(this.ticket.getTrain());
        tc.getRunningTimeLabel().setText(this.ticket.getDepartTime());
        ticketDetailsPanel.add(tc);
        ticketDetailsPanel.add(new SeatCard(this.ticket.getSeat()));
        dateLabel.setText("Depart Date: "+this.ticket.getTravelDate());
        priceLabel.setText("Price: "+this.ticket.getPrice()+" L.E");
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketDetailsPanel = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout ticketDetailsPanelLayout = new javax.swing.GroupLayout(ticketDetailsPanel);
        ticketDetailsPanel.setLayout(ticketDetailsPanelLayout);
        ticketDetailsPanelLayout.setHorizontalGroup(
            ticketDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ticketDetailsPanelLayout.setVerticalGroup(
            ticketDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        priceLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        priceLabel.setText("Ticket Price:");

        dateLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        dateLabel.setText("Depart Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ticketDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JPanel ticketDetailsPanel;
    // End of variables declaration//GEN-END:variables
}
