/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cairomonorail.Train;
import javax.swing.JLabel;

/**
 *
 * @author Go
 */

public class TrainCard extends javax.swing.JPanel {
    Train train;
    /**
     * Creates new form TrainCard
     */
    public TrainCard(Train train) {
        initComponents();
        setTrain(train);
    }

    public Train getTrain() {
        return train;
    }

    public void setTrain(Train train) {
        this.train = train;
        RouteIDLabel.setText("RouteID: "+this.train.getRoute().getId());
        FirstClassNoLabel.setText("FirstClass: "+this.train.getFirstClassSeats());
        BusinessNoLabel.setText("Business: "+this.train.getBusinessSeats());
        EconomyNoLabel.setText("Economy: "+this.train.getEconomySeats());
        RunningTimeLabel.setText("Running Time: "+this.train.getStationsRunningTimes().get(0));
    }

    public JLabel getRunningTimeLabel() {
        return RunningTimeLabel;
    }

    public void setRunningTimeLabel(JLabel RunningTimeLabel) {
        this.RunningTimeLabel = RunningTimeLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RouteIDLabel = new javax.swing.JLabel();
        FirstClassNoLabel = new javax.swing.JLabel();
        BusinessNoLabel = new javax.swing.JLabel();
        EconomyNoLabel = new javax.swing.JLabel();
        RunningTimeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 11, 1));

        jPanel1.setBackground(new java.awt.Color(242, 68, 5));

        RouteIDLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        RouteIDLabel.setText("RouteID");

        FirstClassNoLabel.setText("FirstClass:");

        BusinessNoLabel.setText("Business:");

        EconomyNoLabel.setText("Economy:");

        RunningTimeLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        RunningTimeLabel.setText("Running Time:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstClassNoLabel)
                    .addComponent(RouteIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BusinessNoLabel)
                        .addGap(66, 66, 66)
                        .addComponent(EconomyNoLabel))
                    .addComponent(RunningTimeLabel))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RouteIDLabel)
                    .addComponent(RunningTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstClassNoLabel)
                    .addComponent(BusinessNoLabel)
                    .addComponent(EconomyNoLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BusinessNoLabel;
    private javax.swing.JLabel EconomyNoLabel;
    private javax.swing.JLabel FirstClassNoLabel;
    private javax.swing.JLabel RouteIDLabel;
    private javax.swing.JLabel RunningTimeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
